//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal.Portfolio.Resources.Controllers {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeController_pt_BR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeController_pt_BR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Personal.Portfolio.Resources.Controllers.HomeController.pt-BR", typeof(HomeController_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Technology_br__Architect_ {
            get {
                return ResourceManager.GetString("Technology<br/>Architect.", resourceCulture);
            }
        }
        
        internal static string I_m_here_to_create_meaningful_relationships_with_my_clients_ {
            get {
                return ResourceManager.GetString("I\'m here to create meaningful relationships with my clients.", resourceCulture);
            }
        }
        
        internal static string My_passions___br__Personality_ {
            get {
                return ResourceManager.GetString("My passions &<br/>Personality.", resourceCulture);
            }
        }
        
        internal static string Tech_Arch_br__Projects_ {
            get {
                return ResourceManager.GetString("Tech Arch<br/>Projects.", resourceCulture);
            }
        }
    }
}
